AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway Policy to restrict access to localhost:3000"

Parameters:
  RestApiId:
    Type: String
    Description: "The ID of the API Gateway"

Resources:
  VinotiqueApiPolicy:
    Type: AWS::ApiGateway::RestApiPolicy
    Properties:
      RestApiId: !Ref RestApiId
      Policy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Deny"
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*"
            Condition:
              StringNotEquals:
                aws:Referer: "http://localhost:3000"
          - Effect: "Allow"
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*"
